# This is a basic workflow that is manually triggered

name: compile chihuahua

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        include:
          - targetos: windows
            arch: amd64
    name: chihuahua ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '^1.19'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}
          
          
      - name: run tests
        run: go test ./...

# we build and install in case we want to run it or capture an artifact as we do in the step below. 
      - name: Compile chihuahuad
        run: |
          go build ./...
          go install ./...

# This step is to create a release when a tag is pushed        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: 'Release notes'
          draft: false
          prerelease: false
          
      - name: Upload chihuahuad
        uses: actions/upload-artifact@v2
        with:
          name: chihuahuad-${{ matrix.os }}-${{ matrix.arch }}          
          path: cmd/chihuahuad
      - name: Attach chihuahuad to Release
        id: attach_chihuahuad
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cmd/chihuahuad
          asset_name: chihuahuad-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream