name: Docker Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        uses: docker/setup-docker@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-docker-image:latest .
          docker tag ghcr.io/${{ github.repository }}/my-docker-image:latest ghcr.io/${{ github.repository }}/my-docker-image:${{ github.sha }}

      - name: Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/my-docker-image:latest, ghcr.io/${{ github.repository }}/my-docker-image:${{ github.sha }}
